# Site settings
title: Frank's Blog
email: fwji@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is my own blog. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://frankji.com" # the base hostname & protocol for your site
twitter_username: jwzjwz2003cn
github_username:  jwzjwz2003cn

# Build settings
markdown: kramdown
